name: Lint Markdown
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Actualizado a v4
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v16 # Usa la versión más reciente
        with:
          globs: "**/*.md"
